### ISSUE TITLE
Ignored functions reduce total coverage

### ISSUE THREAD

**Issue by killthekitten** [HunterMcGushion/docstr_coverage#15]
I'd like to maintain a 100% docstr coverage with an exception of ignored functions. I'd then add a check to the CI build, and hopefully forget about it. Currently, the ignored functions add to the total coverage, reducing it by a bit and breaking the build.

Let's say I'd like to ignore all the wrappers in the project:

```
.* \.wrapper
```

Here's the output I get:

```
File: "some/file.py"
 Needed: 17; Found: 12; Missing: 5; Coverage: 70.6%

Overall statistics:
Docstrings needed: 17; Docstrings found: 12; Docstrings missing: 5
Total docstring coverage: 70.6%;  Grade: Very good
```

The ignored functions are correctly filtered from the output, but the total coverage doesn't add up to 100% now.

It might need some attention from @Redysz, but I'd be glad to contribute a patch as well. It's just without any tests in the project it is harder to make changes alone.

**Comment by HunterMcGushion** [comment]
@killthekitten, thanks a lot for reporting this! Definitely a bug! You're absolutely right about the project needing tests, but if you're still interested in making a PR, I'd love to get this issue fixed, as well! Thanks a lot for your time and help!

**Comment by killthekitten** [comment]
@HunterMcGushion I'd like to set up a safety net in form of pytest/flake/black and a couple tests. Do you have any strong opinions on it?

**Comment by HunterMcGushion** [comment]
I am strongly in favor of adding proper tests, Black format checks, and Travis integration! I would absolutely love to work with you on the safety net! If you're on Slack, I just made a new [workspace for DocstrCoverage where we can discuss details](https://join.slack.com/t/docstr-coverage/shared_invite/zt-eo1wjmm9-Zd5AakZAe8wPvJZOeKlZfw). Otherwise, we can certainly collaborate here if that's better for you. Thanks for leading the charge! I've always done tests and formatting checks on my other repos, but when I started this one, I wasn't expecting too many people to use it, and it was a bit of a rush job hahaha so I really appreciate your help!

**Comment by killthekitten** [comment]
@HunterMcGushion I'd go for GH actions instead of Travis. It's proven nice in the projects I work on. I'll set up something in the upcoming days!

**Comment by HunterMcGushion** [comment]
I've heard good things about GH actions, so I'm willing to give it a shot, but I've never used it, so I may need your help setting things up. Thanks for all your work on #16!

**Comment by killthekitten** [comment]
@HunterMcGushion I might be barking up the wrong tree. There's nothing wrong with the coverage calculation in my case, it's only an output problem. Actually, there's two problems, and a user error.

Here's the output when running without the ignore file:

```python
# app/some_file.py

def function_one(fn):
     @wraps
     def wrapper():
           ...
...
``` 

```
File: "app/some_file.py"
 - No docstring for `function_one.wrapper`
 - No docstring for `function_two.wrapper`
 - No docstring for `function_three.wrapper`
 - No docstring for `function_four.wrapper`
 - No docstring for `function_five.wrapper`
 Needed: 17; Found: 12; Missing: 5; Coverage: 70.6%
```

Looking at the above, I wrongly assumed that the regular expression in the ignore file would filter against the string `function_one.wrapper`, i.e. it would filter out nested functions. It doesn't work like that, so the ignore file didn't have any effect. That's the first problem.

The second problem is a weird one. Somehow, the output is filtered when running with the ignore file. It doesn't happen when the file is empty, but as soon as at least one rule has been added, the output disappears. I believe this is fixed in the current master, but not in `1.1.0`.

**Comment by HunterMcGushion** [comment]
You're barking up the right tree, @killthekitten! Thanks for bringing this up. That's definitely weird behavior. Are the other 4 functions (`function_two` -> `function_five`) identical to `function_one`? Also, from your output, it looks like it doesn't complain about the fact that `function_one` itself is missing a docstring. It only cares about the nested `wrapper`. Is that correct? 

Just to make sure we're on the same page, the ignore file contained the string `function_one.wrapper`, correct? Was that prefixed by the filename?

Regarding your second problem, I'm waiting to make another release because I'm working on deprecating the CLI argument names to be dash-separated words, rather than run-ons. Side note, I'd love to hear your thoughts on that. So if it looks like this error is gone in the current master, I'm not terribly worried about it.

**Comment by killthekitten** [comment]
@HunterMcGushion I probably went too abstract with the code. 

The function_one and so on docs were present, the ignore file was `.* \.wrapper`.

**Comment by killthekitten** [comment]
> Side note, I'd love to hear your thoughts on that. 
Kebab case is ❤️ 

This should be closed.
