### ISSUE TITLE
SkipMagic seems not working

### ISSUE THREAD

**Issue by mBouamama** [HunterMcGushion/docstr_coverage#33]
Hi hunter!!!
I try:
`docstr-coverage --skipmagic  MyJWT`

output:
```
File: "C:\Users\xxx\PycharmProjects\xxxxxxx\xxxxxx\MyJWT\Exception.py"
 - No docstring for `InvalidJWT.__init__`
 - No docstring for `InvalidJwtJson.__init__`
 - No docstring for `InvalidParam.__init__`
 - No docstring for `UnknownAlg.__init__`
 Needed: 9; Found: 5; Missing: 4; Coverage: 55.6%
```
Can you help me to solve this problem?

PS: I love your package and i want integrate docstr_coverage to my CI. Do you have a badge like this [![codecov](https://codecov.io/gh/mBouamama/MyJWT/branch/master/graph/badge.svg?token=V7yZJ1bZV9)](https://codecov.io/gh/mBouamama/MyJWT) for docs_str ?

**Comment by HunterMcGushion** [comment]
Hi, @mBouamama! Thanks for opening this issue. Can you try using the `--skipinit` option instead of `--skipmagic`?
It seems that `--skipinit` is missing from the README, which is definitely bad, so thank you for bringing this up. 

Regarding your badge question, you can use the `--badge=<filepath>` option to save a docstring coverage percentage badge SVG to the given filepath. From there, you can include your saved badge in your repo's README.md like so:

```markdown
[![docstr_coverage](<filepath/of/your/saved/badge.svg>)](https://github.com/HunterMcGushion/docstr_coverage)
```

Just replace the `<filepath/of/your/saved/badge.svg>` above with the actual filepath you provided. 
@fabiosangregorio has been looking into a badge that's automatically updated like the Codecov one you mentioned, but for now, you can just keep your badge up to date by overwriting the badge file and committing it with the rest of your changes.

Thanks a lot for bringing these issues up, and thank you for your support!

**Comment by fabiosangregorio** [comment]
Hello @HunterMcGushion , @mBouamama . It has been a while :)
Unfortunately, the shields.io badge for docstr_coverage is stuck until Github implements GraphQL queries on Github Actions (currently only json queries are supported). For now you have to commit the badge svg file to the repo code (either through Github Actions or by running docstr_coverage and committing the file manually).

**Comment by mBouamama** [comment]
Hi @fabiosangregorio , @HunterMcGushion , thx for your response. --skipinit option works!!And thx for --badge option.

**Comment by HunterMcGushion** [comment]
@fabiosangregorio, thank you for the update and for your help! 

@mBouamama, glad to hear `--skipinit` works for you. I'll close this issue once the docs/README have been updated to include it. Thanks again for reporting it.
