### ISSUE TITLE
RFE: Parameter documentation coverage

### ISSUE THREAD

**Issue by jnsnow** [HunterMcGushion/docstr_coverage#5]
Hello!

I'm looking for a toolset that functions like Doxygen for Python, which includes the ability to warn (or error) when generating docs that do not document the semantic meaning of parameter names and return values.

Checking for the presence or absence of docstrings is trivial enough for tools like sphinx, sphinx-autodoc, sphinx-coverage, etc. However, I'm interested in developing an extension -- somewhere, somehow -- that is able to detect cases like the following:

```python
def mystery(a, b, c):
    """mystery returns False if you have the MacGuffin, and True otherwise.
        :param a: The value of the Widget.
        :param b: The value of the Gizmo.
    """
    ...
```

And generating a warning or error that you have missed documenting the `c` parameter or semantically defining the return value.

One of the problems of this idea is that it requires a format specification for docstrings, so I suspect this tool isn't quite the right place to implement something like this, but I wanted to get your opinions on the matter and see if you had ideas about the right place or project to do such a thing would be.

For context: I am a QEMU developer trying to improve documentation quality for our testing and power user suite of Python utilities we use for R&D to make them more accessible for new contributors, and a docstring "linter" to make sure our docs are always up-to-date would help us keep things consistent between hundreds of developers.

See my initial research post to the QEMU list here for background: https://lists.gnu.org/archive/html/qemu-devel/2019-07/msg05468.html

From my initial research it looks like no tools are in wide usage that semantically parse and understand things like parameter (and type), return, or exception annotations.

If you'd like to talk about this further, feel free to reply here OR get in touch via email -- my work address is listed on my github profile.

Thanks!
--js

**Comment by HunterMcGushion** [comment]
@jnsnow, thanks for opening this issue! Early in the project, I considered doing something like what you're talking about, but decided not to for two reasons:

First, like you say, people use different docstring styles, which obviously adds quite a bit of complication. This complication is further complicated by the fact that some people don't even use one of the ~2 generally-accepted docstring styles, and still others might not follow them correctly. To account for this, I believe that such a tool would need to be able to not only handle different docstring styles (NumPy, Google, ReST, etc.), but also validate their syntax. I may be incorrect in that belief, but at the very least, the tool would need to be able to handle different styles (as you already mentioned).

Second (and more importantly), I've never actually had a problem with forgetting a parameter in a docstring. I only ever forget entire docstrings, which is why I wanted `docstr_coverage`. This may be a PyCharm thing, but if I write a function and include a docstring with missing parameters, it warns me that I'm missing parameters, like so:
![Screen Shot 2019-10-01 at 11 28 43 PM](https://user-images.githubusercontent.com/11300915/66022642-724d9500-e4a3-11e9-9d5b-7e37597e3beb.png)
![Screen Shot 2019-10-01 at 11 29 58 PM](https://user-images.githubusercontent.com/11300915/66022648-77aadf80-e4a3-11e9-9763-068f7ead7e01.png)
However, I can omit a docstring entirely with no complaint from PyCharm, so from my perspective, that was the problem that needed to be solved. 

I do understand the value of a tool like the one you're describing, and I would certainly like to add further docstring validation to my CI workflows for both of my libraries. However, I think it would require a significant amount of work to catch a problem for which the user should already be seeing a warning (at least in PyCharm). That said, I'm happy to discuss the matter with you further. Thanks again for reaching out!

**Comment by jnsnow** [comment]
Absolutely, your case makes a lot of sense. I realize this was a bit of an overreach, but I am reaching out to several projects to try to gain an understanding of where a tool like this might fit into the ecosystem and try to understand if pursuing a tool like this would be useful for the community. (And, importantly, find out if any existing project feels that it's within scope already so that I don't have to start a new project only to have someone ask: "Why didn't you just use X?")

It's my experience that in a large open source project, formatting errors and missed parameters unfortunately accrue as developers less familiar with idiomatic python contribute to and extend testing infrastructure and scripting utilities. It's a fact of life that they will get the docstrings "wrong", so having a validating parser for docstrings actually becomes quite a value-add. It's quicker to have a linter yap at you than it is to force every contributor to read a lengthy style guide. Guess-and-check is an especially valid method of writing annotated documentation, in my opinion.

If docstrings can be made to be programmatically consistent, we can programmatically consume them to generate cohesive documentation.

PyCharm is indeed a nice tool, but I am interesting in working this into CI/CD workflows for code quality measurement purposes, so an interactive GUI sadly won't work for that case. If PyCharm uses a standard tool to do its linting on the backend, though, that would be of high interest to me because I'd rather not reinvent the wheel if I don't have to, of course!

Thanks for taking the time to respond! I'm going to mark this as Closed for now, as out of scope for this project.
